backend:
  name: git-gateway
  branch: main

# Tell Netlify about the site
sites:
  - name: friendly-meerkat-7ac490
    api_url: https://api.netlify.com

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
